name: Deploy Vite React App

on:
  push:
    branches: [main] # main 브랜치에 푸시될 때 실행

permissions:
  contents: write # GitHub Pages에 배포하기 위해 필요한 권한

jobs:
  build-and-deploy:
    runs-on: node:18 # Node.js 환경 직접 사용
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
